import { Inter } from "next/font/google"
import "./globals.css";
import { getServerSession } from 'next-auth'
import SessionProvider from './component/SessionProvider'
//import { Geist, Geist_Mono } from "next/font/google";
//import NextLink from 'next/link';
//import { forwardRef } from 'react';
//import { ThemeProvider, createTheme } from '@mui/material/styles';


const inter = Inter({ subsets: ["latin"]})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  const session = await getServerSession()
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>{children}</SessionProvider>
        </body>
    </html>
  );
}



